name: vmba
description: Videcom Mobile Booking App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.0+401



environment:
  flutter: ^3.10.0-10.0.pre.17 # Keep relatively close to master channel version
  sdk: ">=2.17.0"
 # sdk: ">=2.12.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  package_info_plus: ^4.1.0  #^1.4.2 #^1.3.0
  #   The following (store_redirect) could be considered an alternative to open_appstore
  #   which lacks Android V2 embedding support and may get deprecated
  version: ^3.0.2  #^2.0.0
  path_provider: ^2.1.1  #^2.0.5
  connectivity_plus: ^4.0.2  #^2.0.2
  url_launcher: ^6.0.12
  http: ^1.1.0
  intl:
  sqflite:
  webview_flutter:
  #flutter_masked_text: ^0.8.0
  #  provider:
  carousel_slider:  ^4.0.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  flutter_launcher_icons: ^0.13.1 # ^0.9.2


  qr_flutter:

  #credit_card: ^0.1.8
  barcode_widget: ^2.0.1
  country_icons: ^2.0.2
  step_progress_indicator: ^1.0.1
  html: ^0.15.0
  flutter_date_pickers: ^0.4.0
  firebase_messaging: ^14.6.7
  firebase_analytics: ^10.2.1
  firebase_core: ^2.7.0
#  firebase_messaging: ^14.6.7  #^11.1.0
  store_redirect: ^2.0.0
  flutter_local_notifications: ^15.1.1  #^9.0.2
  device_info_plus: ^9.0.3 #^3.1.0
  #firebase_core:  ^2.7.0 #^1.12.0
  flutter_html: ^3.0.0-alpha.5
  timeline_tile: ^2.0.0
  html_unescape: ^2.0.0
  flutter_phosphor_icons: ^0.0.1+6
  launch_review: ^3.0.1
  calendar_date_picker2: ^0.5.3
  #syncfusion_flutter_datepicker: ^23.1.39
  #get: ^4.6.6

dependency_overrides:
  #firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/airswift/images/AirSwift_1024x1024.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/appleWallet.png
    - lib/assets/images/googleWallet.png
    - lib/assets/images/bg.png
    - lib/assets/countryCodes.json
    - lib/assets/images/noNetwork.png
    - lib/assets/blueislands/images/appBar.png
    - lib/assets/blueislands/images/logo.png
    - lib/assets/blueislands/images/app.png
    - lib/assets/blueislands/images/appBarLeft.png
    - lib/assets/blueislands/images/loader.png
    - lib/assets/blueislands/json/countries.json
    - lib/assets/loganair/images/appBar.png
    - lib/assets/loganair/images/logo.png
    - lib/assets/loganair/images/app.png
    - lib/assets/loganair/json/countries.json
    - lib/assets/loganair/images/appBarLeft.png
    - lib/assets/loganair/images/loader.png
    - lib/assets/fastjet/images/loader.png
    - lib/assets/fastjet/images/app.png
    - lib/assets/fastjet/images/appBar.png
    - lib/assets/fastjet/images/logo.png
    - lib/assets/fastjet/images/appBarLeft.png
    - lib/assets/fastjet/json/countries.json
    - lib/assets/HiSky/images/loader.png
    - lib/assets/HiSky/images/app.png
    - lib/assets/HiSky/images/appBar.png
    - lib/assets/HiSky/images/logo.png
    - lib/assets/HiSky/json/countries.json
    - lib/assets/medsky/images/loader.png
    - lib/assets/medsky/images/app.png
    - lib/assets/medsky/images/appBar.png
    - lib/assets/medsky/images/logo.png
    - lib/assets/medsky/json/countries.json
    - lib/assets/aurigny/images/loader.png
    - lib/assets/aurigny/images/app.png
    - lib/assets/aurigny/images/appBar.png
    - lib/assets/aurigny/images/logo.png
    - lib/assets/aurigny/json/countries.json
    - lib/assets/json/countries.json
    - lib/assets/images/payment/mastercard.png
    - lib/assets/images/payment/visa.png
    - lib/assets/images/payment/paystack.png
    - lib/assets/airswift/images/appBar.png
    - lib/assets/airswift/images/logo.png
    - lib/assets/airswift/images/loader.png
    - lib/assets/airswift/images/app.png
    - lib/assets/airswift/json/countries.json
    - lib/assets/airleap/images/appBar.png
    - lib/assets/airleap/images/logo.png
    - lib/assets/airleap/lang/en.json
    - lib/assets/airgotland/json/countries.json
    - lib/assets/airgotland/images/appBar.png
    - lib/assets/airgotland/images/logo.png
    - lib/assets/airgotland/images/loader.png
    - lib/assets/airgotland/lang/en.json
    - lib/assets/airskane/json/countries.json
    - lib/assets/airskane/images/appBar.png
    - lib/assets/airskane/images/logo.png
    - lib/assets/airskane/images/loader.png
    - lib/assets/airskane/lang/en.json
    - lib/assets/airhalland/json/countries.json
    - lib/assets/airhalland/images/appBar.png
    - lib/assets/airhalland/images/logo.png
    - lib/assets/airhalland/images/loader.png
    - lib/assets/airhalland/lang/en.json
    - lib/assets/keylimeair/json/countries.json
    - lib/assets/keylimeair/images/appBar.png
    - lib/assets/keylimeair/images/app.png
    - lib/assets/keylimeair/images/logo.png
    - lib/assets/keylimeair/images/loader.png
    - lib/assets/airleap/json/countries.json
    - lib/assets/airleap/images/appBarLeft.png
    - lib/assets/airleap/images/loader.png
    - lib/assets/buraq/images/appBar.png
    - lib/assets/buraq/images/app.png
    - lib/assets/buraq/images/appBarLeft.png
    - lib/assets/buraq/images/logo.png
    - lib/assets/buraq/images/loader.png
    - lib/assets/unitednigeria/images/appBar.png
    - lib/assets/unitednigeria/images/app.png
    - lib/assets/unitednigeria/images/logo.png
    - lib/assets/unitednigeria/images/loader.png
    - lib/assets/icons/visa.png
    - lib/assets/icons/mastercard.png
    - lib/assets/icons/amex.png
    - lib/assets/icons/discover.png
    - lib/assets/icons/chip.png
    - lib/assets/buraq/json/countries.json

    - lib/assets/lang/en.json
    - lib/assets/lang/fr.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
