name: vmba
description: Videcom Mobile Booking App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
#  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #package_info: #^0.4.0+5 
  package_info: '>=0.4.3 <2.0.0' 
  open_appstore: ^1.0.2
  version: ^1.0.0
  path_provider: ^1.6.22
  connectivity: ^0.4.3+4
  url_launcher: ^5.0.3
  http:
  intl:
  sqflite: 
  flutter_date_pickers: <0.0.6
  webview_flutter:
  flutter_masked_text: ^0.8.0
#  provider:
  carousel_slider: ^1.3.0
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  shared_preferences: ^0.5.3+4
  flutter_launcher_icons: ^0.8.0

  #barcode_generator: ^0.2.7
  # barcode_generator:
  #   git:
  #     url: git://github.com/iHunterX/barcode_generator.git
  qr_flutter:
    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  credit_card: ^0.1.8
  #core_card_io: ^0.0.2
  flutter_paystack: ^1.0.4+1
  flutter_holo_date_picker: ^0.3.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/AirSwift_1024x1024.png"
#   image_path: "lib/assets/icon/loganair_1024x1024.png"
#  image_path: "lib/assets/icon/AirLeap_1024x1024.png"
# flutter pub run flutter_launcher_icons:main -f launch_icons_airleap.yaml
# flutter pub run flutter_launcher_icons:main -f launch_icons_airswift.yaml
# flutter pub run flutter_launcher_icons:main -f launch_icons_loganair.yaml


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    
    - lib/assets/blueislands/images/appBar.png
    - lib/assets/blueislands/images/logo.png
    - lib/assets/blueislands/images/background.png
    - lib/assets/blueislands/images/appBarLeft.png
    - lib/assets/blueislands/images/loader.png
    - lib/assets/blueislands/json/countries.json
    - lib/assets/ibomair/images/appBar.png
    - lib/assets/ibomair/images/logo.png
    - lib/assets/ibomair/images/loader.png
    - lib/assets/ibomair/images/background.png
    - lib/assets/ibomair/json/countries.json
    - lib/assets/loganair/images/appBar.png
    - lib/assets/loganair/images/logo.png
    - lib/assets/loganair/images/background.png
    - lib/assets/loganair/json/countries.json
    - lib/assets/loganair/images/appBarLeft.png
    - lib/assets/loganair/images/loader.png
    - lib/assets/json/countries.json
    - lib/assets/images/payment/mastercard.png
    - lib/assets/images/payment/visa.png
    - lib/assets/images/payment/paystack.png
    - lib/assets/airswift/images/appBar.png
    - lib/assets/airswift/images/logo.png
    - lib/assets/airswift/images/loader.png
    - lib/assets/airswift/images/background.png
    - lib/assets/airswift/json/countries.json
    - lib/assets/airleap/images/appBar.png
    - lib/assets/airleap/images/logo.png
    - lib/assets/airleap/images/background.png
    - lib/assets/airleap/json/countries.json
    - lib/assets/airleap/images/appBarLeft.png
    - lib/assets/airleap/images/loader.png
    - lib/assets/lang/en.json
    - lib/assets/lang/fr.json

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
